# MATH 210 Introduction to Mathematical Computing

## March 10, 2017

1. More linear algevra in SciPy
  * Matrix powers, eigenvalues and eigenvectors
2. Examples
  * Projections
  * Least squares regression
3. Exercises

In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import scipy.linalg as la

## 1. More linear algebra in SciPy

We've seen matrix multiplication of NumPy arrays using the `@` operator:

In [3]:
M = np.array([[2,1],[-2,5]])
M

array([[ 2,  1],
       [-2,  5]])

In [4]:
M @ M

array([[  2,   7],
       [-14,  23]])

Remember that `M**2` is an array operation on NumPy arrays and compute the squares of each entry.

In [5]:
M**2

array([[ 4,  1],
       [ 4, 25]])

What if we want to compute higher powers of $M$ (as matrix multiplication) like $M^3 = MMM$? We need the function `numpy.linalg.matrix_power`.

We need to use `numpy.linalg.matrix_power`:

In [6]:
np.linalg.matrix_power(M,2)

array([[  2,   7],
       [-14,  23]])

In [7]:
from numpy.linalg import matrix_power as mpow

In [8]:
mpow(M,2)

array([[  2,   7],
       [-14,  23]])

In [9]:
mpow(M,5)

array([[ -538,   781],
       [-1562,  1805]])

### Example: Use diagonalization to compute matrix powers

If $M$ is an $n$ by $n$ matrix with $n$ real eigenvalues and $n$ distinct eigenvectors, then we can diagonalize $M$ as $M = PDP^{-1}$ where the columns of $P$ are the (unit) eigenvectors of $M$ and $D$ has corresponding eigenvalues along the diagonal.

Let's use this to construct a matrix with given eigenvalues $\lambda_1 = 3, \lambda_2 = 1$ and eigenvectors $v_1 = [1,1]^T, v_2 = [1,-1]^T$.

In [11]:
P = np.array([[1,1],[1,-1]])
P

array([[ 1,  1],
       [ 1, -1]])

In [12]:
D = np.diag((3,1))
D

array([[3, 0],
       [0, 1]])

In [13]:
M = P @ D @ la.inv(P)
M

array([[ 2.,  1.],
       [ 1.,  2.]])

In [15]:
evals, evecs = la.eig(M)

In [16]:
evals

array([ 3.+0.j,  1.+0.j])

In [17]:
evecs

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

Let's compute high powers of $M$ in two ways: (1) just by computing $M^k = MMM\cdots$ by matrix multiplication, (2) by $M = PDP^{-1}$ and $M^k = PD^kP^{-1}$

In [31]:
k = 15

In [32]:
mpow(M,k)

array([[ 7174454.,  7174453.],
       [ 7174453.,  7174454.]])

In [33]:
Pinv = la.inv(P)

In [34]:
P @ D**k @ Pinv

array([[ 7174454.,  7174453.],
       [ 7174453.,  7174454.]])

## 2. Examples

### Projection

The formula to project a vector $v$ onto a vector$w$ is:

$$
\mathrm{proj}_w(v) = \frac{v \cdot w}{w \cdot w} w
$$

Let's write a function called `proj` which computes the projection $v$ onto $w$.

In [42]:
def proj(v,w):
    """Projection vector v onto w."""
    v = np.array(v)
    w = np.array(w)
    return np.sum(v * w) / np.sum(w * w) * w # Or (v @ w)/(w @ w) * w

In [43]:
proj([1,2,3],[1,1,1])

array([ 2.,  2.,  2.])

### About 1D and 2D NumPy arrays and the @ operator

Notice that the `@` operator compute the dot product of 1D NumPy arrays.

In [44]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [45]:
x.ndim

1

In [46]:
x.shape

(3,)

In [47]:
x @ x

14

In [48]:
x.reshape(3,1) @ x.reshape(1,3)

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [49]:
y = x.reshape(1,3)

In [50]:
y.ndim

2

In [51]:
y.shape

(1, 3)

In [52]:
y

array([[1, 2, 3]])

In [53]:
x

array([1, 2, 3])