# MATH210 Introduction to Mathematical Computing

## March 15, 2017

1. More about NumPy array
  * Dimension
  * Shape and reshape
  * hstack
  * vstack
  * fancy indexing
2. More examples from linear algera

In [50]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import scipy.linalg as la

## 1. More about NumPy arrays

### Dimension

NumPy arrays can have any number of dimensions. 1D NumPy array is a list:

In [2]:
v = np.array([1,2,3])
v

array([1, 2, 3])

2D NumPy array is like matrix:

In [3]:
M = np.array([[1,2,3],[6,7,1]])
M

array([[1, 2, 3],
       [6, 7, 1]])

In [4]:
v.ndim

1

In [5]:
M.ndim

2

A 3D NumPy array is like a cube of numbers:

In [7]:
N = np.random.randint(0,10,(2,2,2))
N

array([[[1, 9],
        [6, 5]],

       [[3, 5],
        [6, 3]]])

In [9]:
N.ndim

3

### Shape and reshape

We can see what shape a NumPy array has using the `shape` attribute and we can change the shape of a array using the `reshape` method:

In [10]:
M.shape

(2, 2, 2)

In [11]:
v.shape

(3,)

In [12]:
w = np.arange(0,36)
w

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [15]:
x = w.reshape(6,6)
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [16]:
x.shape

(6, 6)

In [18]:
w.shape

(36,)

### hstack and vstack

We can build bigger arrays out of smaller arrays by stacking them vertically and horizontally. For example, we can vertically stack 3 1D arrays into a matrix.

In [20]:
x = np.array([1,1,1])
y = np.array([2,2,2])
z = np.array([3,3,3])

In [21]:
np.vstack((x,y,z))

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [22]:
np.hstack((x,y,z))

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

Let's use `hstack` and `vstack` to build a block matrix $\begin{bmatrix} A & B \\ C & D \end{bmatrix}$

In [28]:
A = np.ones(4).reshape(2,2)
B = 2*np.ones(4).reshape(2,2)
C = 3*np.ones(4).reshape(2,2)
D = 4*np.ones(4).reshape(2,2)
A

array([[ 1.,  1.],
       [ 1.,  1.]])

In [30]:
r1 = np.hstack((A,B))
r1

array([[ 1.,  1.,  2.,  2.],
       [ 1.,  1.,  2.,  2.]])

In [31]:
r2 = np.hstack((C,D))
r2

array([[ 3.,  3.,  4.,  4.],
       [ 3.,  3.,  4.,  4.]])

In [32]:
np.vstack((r1,r2))

array([[ 1.,  1.,  2.,  2.],
       [ 1.,  1.,  2.,  2.],
       [ 3.,  3.,  4.,  4.],
       [ 3.,  3.,  4.,  4.]])

### Fancy indexing

We can access the entry in the $i$th row and $j$th column using the bracket notation `A[i,j]`.

In [38]:
A = np.random.randint(-9,10,(4,4))
A

array([[-5, -6, -9,  4],
       [-3, -1, -5,  3],
       [ 9, -3, -7, -8],
       [ 1, -1,  3, -2]])

In [39]:
A[0,0]

-5

In [40]:
A[2,3]

-8

We can pass in list of indices to access certain rows and columns:

In [43]:
A[[1,3],:]

array([[-3, -1, -5,  3],
       [ 1, -1,  3, -2]])

We can also pass in a mask which is just a boolean array.

In [45]:
A > 0

array([[False, False, False,  True],
       [False, False, False,  True],
       [ True, False, False, False],
       [ True, False,  True, False]], dtype=bool)

In [46]:
A[A > 0]

array([4, 3, 9, 1, 3])

In [47]:
A

array([[-5, -6, -9,  4],
       [-3, -1, -5,  3],
       [ 9, -3, -7, -8],
       [ 1, -1,  3, -2]])

In [48]:
A[np.array([0,1,2,3]) !=2,:]

array([[-5, -6, -9,  4],
       [-3, -1, -5,  3],
       [ 1, -1,  3, -2]])

## 2. More examples from linear algebra

The LU factorization of a matrix $A$ is decomposes $A$ into 3 matrices

$$
A = PLU
$$

where $P$ is a perpmuation matrix, $L$ is lower triangular and $U$ is upper triangular. The matrix $U$ is (more or less) the row echelon form of A.

In [49]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [51]:
P, L, U = la.lu(A)

In [52]:
P

array([[ 0.,  1.],
       [ 1.,  0.]])

In [53]:
L

array([[ 1.        ,  0.        ],
       [ 0.33333333,  1.        ]])

In [54]:
U

array([[ 3.        ,  4.        ],
       [ 0.        ,  0.66666667]])

In [55]:
P @ L @ U

array([[ 1.,  2.],
       [ 3.,  4.]])

For example, we can use th $LU$ factorization to find a basis for the span of vectors $v_1$, $\dots$, $v_n$ by stacking the vectors into the rows a matrix $A$ and then computing $U$ in the $LU$ factorization.

In [56]:
u1 = np.random.randint(0,9,5)
u2 = np.random.randint(0,9,5)
u3 = np.random.randint(0,9,5)

In [58]:
A = np.vstack((u1,u2,u3))
A

array([[8, 2, 8, 4, 4],
       [6, 0, 6, 1, 4],
       [7, 7, 8, 5, 1]])

In [59]:
P,L,U = la.lu(A)

In [60]:
U

array([[ 8.        ,  2.        ,  8.        ,  4.        ,  4.        ],
       [ 0.        ,  5.25      ,  1.        ,  1.5       , -2.5       ],
       [ 0.        ,  0.        ,  0.28571429, -1.57142857,  0.28571429]])